services:
  frontend:
    image: ${DOCKER_HUB_USERNAME}/${IMAGE_NAME}:latest
    container_name: ${APP_NAME}_frontend
    restart: unless-stopped
    networks:
      - fullstack-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    volumes:
      - ./nginx.frontend.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - fullstack-network

networks:
  fullstack-network:
    external: true
