services:
  frontend:
    image: ${DOCKER_PROVIDER_USERNAME}/${IMAGE_NAME}:${IMAGE_TAG}
    container_name: ${APP_NAME}_frontend
    restart: unless-stopped
    networks:
      - ${NETWORK_NAME}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    volumes:
      - ./nginx.frontend.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot
      - ./logs/nginx:/var/log/nginx
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    networks:
      - ${NETWORK_NAME}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  ${NETWORK_NAME}:
    external: true
