x-common: &common
  restart: unless-stopped
  networks:
    - fullstack-network
  logging: &default-logging
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"
  deploy: &default-resources
    resources:
      limits:
        cpus: '0.5'
        memory: 512M
      reservations:
        cpus: '0.25'
        memory: 256M

services:
  frontend:
    <<: *common
    image: ${FRONTEND_IMAGE}
    container_name: ${APP_NAME}_frontend
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://abdeel.me/api}
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:3000 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    logging:
      <<: *default-logging
      options:
        tag: "${APP_NAME}-frontend"

  nginx:
    <<: *common
    image: nginx:alpine
    container_name: ${APP_NAME}_nginx
    depends_on:
      frontend:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.frontend.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot
      - ./logs/nginx:/var/log/nginx
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    healthcheck:
      test: [ "CMD-SHELL", "curl -fail http://localhost:80 || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 3
    logging:
      <<: *default-logging
      options:
        tag: "${APP_NAME}-nginx"

networks:
  fullstack-network:
    external: true