name: CI - NextJS frontend build, push

on:
  push:
    branches: [develop, main]
  workflow_dispatch:

env:
  IMAGE_NAME: nextjs-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_PROVIDER_NAME }}/${{ secrets.DOCKER_PROVIDER_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,latest
            type=sha,format=short

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_PROVIDER_USERNAME }}
          password: ${{ secrets.DOCKER_PROVIDER_TOKEN }}

      - name: 🚀 Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_PROVIDER_NAME }}/${{ secrets.DOCKER_PROVIDER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline

      - name: Save image tag for CD workflow
        run: |
          echo "${{ steps.meta.outputs.tags }}" | tr ',' '\n' | grep 'sha-' | sed 's/.*://g' > image_tag.txt


      - name: 📦 Upload deployment files
        uses: actions/upload-artifact@v4
        with:
          name: deploy-files
          path: |
            image_tag.txt

      - name: 🔎 Scan image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_PROVIDER_NAME }}/${{ secrets.DOCKER_PROVIDER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          format: "table"
          exit-code: "1"
          severity: "CRITICAL"
